### ISSUE TITLE
Level 51 is Impossible

### ISSUE THREAD

**Issue by potocpav** [keera-studios/magic-cookies#14]
Spent way too much time on it, proved it using two different methods. Either 51 is impossible, or I'm missing some hidden game mechanic.

![Screenshot_20191202-225901_Magic cookies!](https://user-images.githubusercontent.com/4094619/69998773-62136e00-1557-11ea-8f44-7a72ac43660b.jpg)

How can I get past level 51?

The game is great btw :)

**Comment by myroslambda** [comment]
Hi @potocpav !

Thanks! Glad you like it!

You're right, there was a problem in that level :S Sorry about that.

We've uploaded a new version as a public beta that you can try: https://play.google.com/apps/testing/uk.co.keera.games.magiccookies. Let me know if you cannot see it or sign up.

Unfortunately, Google now requires that we also upload both 32bit and 64bit binaries, so the download will be much bigger than the one before. We are looking into this right now to get them back to their original size.

If that version works well, we'll push that to everybody :)

EDIT: Google Play is not letting me see this link, but it should work soon. I believe this is just because it was rolled out too recently, I'll check again in 1-2 hours.

**Comment by potocpav** [comment]
Sounds great! 

The link doesn't work for me. I don't know if I have to wait, but it seems unlikely given the error message:

![Screenshot from 2019-12-04 13-00-46](https://user-images.githubusercontent.com/4094619/70140959-35b23b80-1696-11ea-91ac-e8012de9d75f.png)

**Comment by myroslambda** [comment]
I see the same thing as a user, and I absolutely agree: the message does not seem to indicate an update is in progress. I searched and people on stackoverflow are saying that they just had to wait a little.

"After publishing an open, closed, or internal test for the first time, it may take a few hours for your test link to be available to testers. If you publish additional changes, they may take several hours to be available for testers." (that's from Google, not stackoverflow)

This app was never published as a beta. (We had a separate game on the play store for beta testers that we will now retire.)

I cannot see anything in the development settings on Google Play that suggests that anything is wrong. The problem only manifests when I click on the link. It says the beta is rolled out to everyone, and that it is an open beta. I'll check again in 1h or so.

**Comment by potocpav** [comment]
It works now. I downloaded and installed the beta. 

Level 51 is different and solvable now, so you can close this issue.

Thank for the extremely quick fix:)

**Comment by myroslambda** [comment]
Glad to hear it works!

**Comment by myroslambda** [comment]
Sorry for touching a closed issue. I just wanted to let you know, @potocpav, that there's a new version 1.44 that makes the app a bit smaller (just pushed so, again, it may take some time to show up on the store).

It's only for beta testers at the moment.

**Comment by potocpav** [comment]
I will try it today and report any issues if they arise.
