### ISSUE TITLE
Level selection menu, input detection, portrait (was: Can I go back to a level that I've already done?)

### ISSUE THREAD

**Issue by DougBurke** [keera-studios/magic-cookies#6]
I wanted to show my kids how to play the game, but was unable to move back to Level 1. I expected to be able to go to the Level page and select one of the levels I've already done, but this did not work; should it have? If not, can it? Or am I missing something blindingly obvious?

This is on a Nexus 7 running Android 5.1

**Comment by ivanperez-keera** [comment]
You should be able to, that's what the level menu option is for.

Going to _Level_ on the main menu should show the levels that you've already completed (highlighted), and clicking on a highlighted level should open it.

You don't lose the last completed level when you do this: if you've completed till, say, the 17th and go back to the 10th, you'll still be able to go up to the 17th again.

I get from you message that it may not be working properly. _(Note: Somehow nexus phones are giving us a hard time.)_
- What are the exact symptoms?
  _(Note: I'm trying to understand what happens beyond "it does not work".)_
- When you click on a highlighted level (that is, one you've completed), what does it do? Does the game keep responding after this? Can you go back to the main menu by pressing the back key?
  _(Note: I'm trying to understand if the game hangs, or whether it's an issue with input detection, etc.)_
- Try to turn the phone sideways. The menu list is quite long, I find it easier (more accurate) to play the game in landscape. _(Note: if this is the problem, maybe having a level-selection screen with larger texts, and possibly several screens, might help.)_

Thanks for reporting this, by the way :) And for showing it to your kids. I now wrote this game because someone showed it to me when I was a kid and I absolutely loved it.

**Comment by ivanperez-keera** [comment]
I just checked on another phone and there seems to be a problem with the input in portrait mode. I'm going to turn this into a bug, fix it, and push a new version. If yours is the same problem, it should work fine in landscape mode.

**Comment by DougBurke** [comment]
Aha. I can confirm that when in landscape mode the level menu works. The
screen on the nexus 7 is large enough that portrait mode was the obvious
choice for me!

Thanks for the quick response,
Doug

**Comment by ivanperez-keera** [comment]
Hi Doug. I've fixed this. A new version, 1.25, has been uploaded to Google Play. There is a delay of several hours until it becomes available. The "What's new" section on Google Play should indicate the latest available version.

Please let me know if something fails, re-opening this bug opening a new one as you see fit.
