### ISSUE TITLE
does not start on Asus Zenfone 6 (Intel Atom)

### ISSUE THREAD

**Issue by sannysanoff** [keera-studios/magic-cookies#7]
Blank screen.
Logcat:

....
D/dalvikvm(13959): Added shared lib /data/app-lib/uk.co.keera.games.magiccookies-1/libmymain.so 0x43a0e040
D/dalvikvm(13959): No JNI_OnLoad found in /data/app-lib/uk.co.keera.games.magiccookies-1/libmymain.so 0x43a0e040, skipping init
V/keera.cookiesout(13959): onCreate():null
V/keera.cookiesout(13959): onResume()
E/IMGSRV  (13959): :0: PVRDRMOpen: TP3, ret = 47
E/IMGSRV  (13959): :0: PVRDRMOpen: TP3, ret = 50
E/IMGSRV  (13959): :0: PVRDRMOpen: TP3, ret = 51
E/IMGSRV  (13959): :0: PVRDRMOpen: TP3, ret = 51
E/IMGSRV  (13959): :0: PVRDRMOpen: TP3, ret = 51
E/IMGSRV  (13959): :0: PVRDRMOpen: TP3, ret = 53
D/OpenGLRenderer(13959): Enabling debug mode 0
V/keera.cookiesout(13959): surfaceCreated()
V/keera.cookiesout(13959): surfaceChanged()
V/keera.cookiesout(13959): pixel format RGB_565
V/keera.cookiesout(13959): Window soze:720x1280
I/SDL     (13959): SDL_Android_Init()
I/SDL     (13959): SDL_Android_Init() finished!
D/sdl     (13959): Hello
V/keera.cookiesout(13959): calledShowHome()
I/SDL/APP (13959): Added joystick Android Accelerometer with device_id -2147483648

nothing after that point.

**Comment by sannysanoff** [comment]
on 5th time, launched...

**Comment by ivanperez-keera** [comment]
Thanks a lot for reporting this, Sanny, and especially for sending a logcat.

I'm looking into it.

**Comment by ivanperez-keera** [comment]
It turns out that hsSDL2 does not report all possible events, and some are making the application fail. Once it fails, it does not always recreate the game resources from scratch, which leaves it in an inconsistent state. 

When that happens, try to kill the app (context button, and slide Magic Cookies sideways [1]) and relaunch it. (Relauching without killing it first won't work!)

We'll make the necessary changes to the SDL2 haskell bindings and publish both our changes and a new version of the app.

References:
- How to kill an app without launching the task manager: http://cdn5.howtogeek.com/wp-content/uploads/2013/06/384x640xandroid-multitasking-end-app.png.pagespeed.ic.xO0ab04Ok9.png

**Comment by ivanperez-keera** [comment]
Would you mind giving the latest version a try?

I think I have the latest bug tracked down, but I expect the latest public version to be much more stable than the one you tried.

It turns out that in Haskell you almost never have to worry about garbage collection, but in this case the GC is freeing data while it's still necessary :(

Again, I'll try to change the SDL2 bindings to address that too. It manifests very rarely on phones, that's why it was so hard to detect.

**Comment by sannysanoff** [comment]
Hi there! 
I already sold my ASUS (for the reason unrelated to magic cookies).
Fresh installation on Samsung (64bit arm) went fine, program works without issues from first time.
Goog luck!
